#!/usr/bin/env python3

import os
import sys

import exifread

class Coordinate():
	def __init__(self):
		self.value = None
		self.is_negative = False

	def to_string(self):
		deg, min, sec_frac = self.value[1:-1].split(', ')

		sec_dec = 0

		if '/' in sec_frac:
			num, den = sec_frac.split('/')
			sec_dec = float(num) / float(den)
		else:
			sec_dec = int(sec_frac)

		return '{}{:>3}°{:>2}\'{:6.2f}"'.format(
			'-' if self.is_negative else ' ',
			int(deg),
			int(min),
			sec_dec * 6
		)

def main():
	files = sys.argv[1:]

	if len(files) == 0: # gets all files in directory if no arguments given
		files = [f for f in os.listdir('.') if os.path.isfile(f)]

	images = []
	longest = 0

	for file in sorted(files):
		f = open(file, 'rb')

		latitude  = Coordinate()
		longitude = Coordinate()

		for key, value in exifread.process_file(f).items():
			if key == 'GPS GPSLongitude':
				longitude.value = value.printable
			elif key == 'GPS GPSLatitude':
				latitude.value = value.printable
			elif key == 'GPS GPSLongitudeRef':
				longitude.is_negative = str(value) == 'W'
			elif key == 'GPS GPSLatitudeRef':
				latitude.is_negative = str(value) == 'S'

		if latitude.value and longitude.value:
			longest = max(len(file), longest)

			images.append((file, latitude, longitude))

	for image in images:
		file, latitude, longitude = image

		print('{}: {}, {}'.format(
			file.rjust(longest),
			latitude.to_string(),
			longitude.to_string()
		))

if __name__ == '__main__':
	main()