#!/usr/bin/env python3

import os
import re
import sys

def main():
	args = sys.argv[1:]

	# no arguments given
	if len(args) == 0:
		print_usage()
		return

	file = args[0]

	# adds file extension if omitted
	if not file.endswith('.iso'):
		file += '.iso'

	if not os.path.exists(file):
		print(f'File does not exist: {file}')
		return

	name = os.path.splitext(file)[0]

	tracks = read_directory(name)
	sheet = make_cue_sheet(name, tracks)

	try:
		write_file(name, sheet)

		print(f'Wrote cue sheet: {name}.cue')
	except:
		print(f'Could not write cue sheet: {name}.cue')

def print_usage():
	print('Usage: mkcue <iso file>\n\n' \
	      'Files should be named like:\n\n' \
	      'Ecco the Dolphin.iso\n' \
	      'Ecco the Dolphin 02.wav\n' \
	      'Ecco the Dolphin 03.wav\n' \
	      'Ecco the Dolphin 04.wav ...\n\n' \
	      'Audio files can be in WAV, MP3, AIFF, or FLAC format.')

def make_cue_sheet(name, tracks):
	sheet = f'FILE "{name}.iso" BINARY\n' \
	         '  TRACK 01 MODE1/2048\n' \
	         '      INDEX 01 00:00:00\n'

	if len(tracks) > 1:
		sheet += '      POSTGAP 00:02:00\n'

	count = 1

	for file in tracks:
		count += 1

		extension = os.path.splitext(file)[1]

		if extension == 'mp3':
			format = 'MP3'
		elif extension == 'aif' or extension == 'aiff' or extension == 'aifc':
			format = 'AIFF'
		else:
			format = 'WAVE'

		sheet += f'FILE "{file}" {format}\n'
		sheet += f'  TRACK {count:02d} AUDIO\n'

		if count == 2:
			sheet += '    PREGAP 00:02:00\n'

		sheet += '    INDEX 01 00:00:00\n'

	return sheet

def read_directory(name):
	escaped = re.escape(name)
	pattern = re.compile(rf'^{escaped} \d\d\.(wav|mp3|aif(f|c)?|flac)$')

	files = [f for f in os.listdir('.') if re.match(pattern, f)]

	return sorted(files)

def write_file(name, sheet):
	with open(f'{name}.cue', 'w') as f:
		f.write(sheet)

if __name__ == '__main__':
	main()